#!/usr/bin/perl


use Modern::Perl;
use File::Basename;

use lib dirname(__FILE__).'/../lib';

use Config::IniFiles;
use App::PPBuild;
use Net::Domain::ES::ccTLD;
use PlanetaLinux;

my $dir = dirname(__FILE__);

open my $fh, "<", $dir."/../config/countries.list"
	or die "Couldn't read the countries list.";

my $r = {};

my $all = [];

while(<$fh>) {
	chomp;
	my $c_id = $_;
	
	my $c_name = find_name_by_cctld( $c_id )
		or die "Couldn't find the name in Spanish for the ccTLD: `$c_id'. I better die.\n";
		
	task $c_id,
		"Builds the Planeta Linux instance for: `$c_name'",
		sub {
			say "running $c_id!";
			
			my $pl = PlanetaLinux->new({
				countries => [$c_id],
			});
			
			$pl->run;
				
			say "done!";
		};
	
	push @$all, $c_id;
		
}

task 'all',
	"Builds all Planeta Linux instances.",
	sub {
		say "running all instances!";
		my $pl = PlanetaLinux->new({
			countries => $all,
		});
		$pl->run;
		say "done!!1";
	};


do_tasks();

1;